# Generated by Django 4.2.30 on 2026-05-02 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0001_initial'),
        ('core', '0002_booking_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gadget',
            name='category',
        ),
        migrations.AlterField(
            model_name='booking',
            name='gadget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='gadgets.gadget'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Gadget',
        ),
    ]
