# Generated by Django 4.2.7 on 2026-05-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_booking_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned')], db_index=True, default='pending', max_length=20),
        ),
    ]
